#!/bin/bash
#
#  modem gps service on solid sense status request
#
# functions

usage () {
	echo "${PROG_NAME}:"
	echo "    -h|--help			:display this help"
	echo "    -l|--list                     :list available networks"
	echo "    -n|--network                  :select an network"
	echo "    -r|--rat                      :select a RAT (GSM/UTRAN/LTE)"
	echo "	  no arguments			:print the modem status"
	exit 1
}

options=$(getopt -l "help,list,network:,rat:" -o "hln:r:" -- "${@}")
eval set -- "${options}"

COMMAND="status"
NETWORK=""
RAT=""
OPT1=""
OPT2=""

while true
do
	case "${1}" in
		-h|--help )
			usage
			;;
		-l|--list )
			COMMAND="operator"
			;;
		-n|--network )
			shift
			NETWORK="${1}"
			;;
		-r|--rat )
			shift
			RAT="${1}"
			;;
		\? )
			usage
			;;
		: )
			echo "Invalid option: ${OPTARG} requires an argument" 1>&2
			;;
		-- )
			shift
			break
			;;
		* )
			break
			;;
	esac
	shift
done

if [ -n "${NETWORK}" ]; then
	COMMAND="operator"
	OPT1=${NETWORK}
fi
if [ -n "${RAT}" ]; then
	if [ -z "${NETWORK}" ]; then
		COMMAND="operator"
		OPT1="CURRENT"
		OPT2=${RAT}
	else
		OPT2=${RAT}
	fi
fi
echo "${COMMAND} ${OPT1} ${OPT2}"

python3 /opt/SolidSense/modem_gps/Modem_Service_Client.py 127.0.0.1:20231 ${COMMAND} "${OPT1}" ${OPT2}
